export const flashSaleProducts = [
  {
    id: "havit-gamepad-1",
    name: "HAVIT HV-G92 Gamepad",
    category: "electronics",
    image: "/13.png",
    price: 120,
    oldPrice: 160,
    discountPercent: 40,
    rating: 5,
    reviewCount: 88,
    addToCartVisible: true,
  },
  
  {
    id: "ak900-keyboard",
    name: "AK-900 Wired Keyboard",
    category: "electronics",
    image: "/3.png",
    price: 960,
    oldPrice: 1160,
    discountPercent: 35,
    rating: 4,
    reviewCount: 75,
  },
  {
    id: "ips-monitor",
    name: "IPS LCD Gaming Monitor",
    category: "electronics",
    image: "/4.png",
    price: 370,
    oldPrice: 400,
    discountPercent: 30,
    rating: 5,
    reviewCount: 99,
  },
  {
    id: "s-series-chair",
    name: "S-Series Comfort Chair",
    category: "home",
    image: "/10.png",
    price: 375,
    oldPrice: 400,
    discountPercent: 25,
    rating: 4,
    reviewCount: 99,
  },
];

export const bestSellingProducts = [
  {
    id: "north-coat",
    name: "The North Coat",
    category: "women",
    image: "/1.png",
    price: 260,
    oldPrice: 360,
    rating: 5,
    reviewCount: 65,
  },
  {
    id: "gucci-bag",
    name: "Gucci Duffle Bag",
    category: "men",
    image: "/2.png",
    price: 960,
    oldPrice: 1160,
    rating: 5,
    reviewCount: 65,
  },
  {
    id: "cpu-cooler",
    name: "RGB Liquid CPU Cooler",
    category: "electronics",
    image: "/1.png",
    price: 160,
    oldPrice: 170,
    rating: 5,
    reviewCount: 65,
  },
  {
    id: "bookshelf",
    name: "Small Bookshelf",
    category: "home",
    image: "/4.png",
    price: 360,
    rating: 5,
    reviewCount: 65,
  },
];

export const exploreProducts = [
  {
    id: "dog-food",
    name: "Breed Dry Dog Food",
    category: "groceries",
    image: "/5.png",
    price: 100,
    rating: 3,
    reviewCount: 35,
  },
  {
    id: "dslr-camera",
    name: "CANON EOS DSLR Camera",
    category: "electronics",
    image: "/6.png",
    price: 360,
    rating: 5,
    reviewCount: 95,
    addToCartVisible: true,
  },
  {
    id: "gaming-laptop",
    name: "ASUS FHD Gaming Laptop",
    category: "electronics",
    image: "/7.png",
    price: 700,
    rating: 5,
    reviewCount: 325,
  },
  {
    id: "curology-set",
    name: "Curology Product Set",
    category: "beauty",
    image: "/8.png",
    price: 500,
    rating: 4,
    reviewCount: 145,
  },
  {
    id: "soccer-cleats-1",
    name: "Jr. Zoom Soccer Cleats",
    category: "sports",
    image: "/9.png",
    price: 1160,
    rating: 5,
    reviewCount: 35,
    colors: ["#EAB308", "#DB4444"],
  },
  {
    id: "soccer-cleats-2",
    name: "Jr. Zoom Pro Cleats",
    category: "sports",
    image: "/10.png",
    price: 1160,
    rating: 5,
    reviewCount: 35,
    colors: ["#EAB308", "#DB4444"],
  },
  {
    id: "gamepad-2",
    name: "GP11 Shooter USB Gamepad",
    category: "electronics",
    image: "/11.png",
    price: 660,
    rating: 5,
    reviewCount: 55,
    isNew: true,
    colors: ["#000000", "#DB4444"],
  },
  {
    id: "satin-jacket",
    name: "Quilted Satin Jacket",
    category: "women",
    image: "/12.png",
    price: 660,
    rating: 5,
    reviewCount: 55,
    colors: ["#166534", "#DB4444"],
  },
];